### ISSUE TITLE
Not working with android 6

### ISSUE THREAD

**Issue by davidmricardo** [tblanchard/zebralink#3]
Hi,

I have an app working fine with android 4 and 5 but in android 6 it never finds the printer! It blocks on the discover method and doesn't give neither an error nor a success it just sits there trying to find the printer.

What can I do to solve this?

**Comment by tblanchard** [comment]
Make sure you have the latest libraries from zebra is all I can tell you.  I'm not working with that client anymore so I don't even have a printer to test with.

**Comment by davidmricardo** [comment]
I've resolved it!

I did what you sugest, but I had to add two permissions in my app Manifest!
I've made a pull request so the plugin can have the latest sdk to everyone!

Thanks,
Best regards,
David

**Comment by phoenixtrigo** [comment]
Hi @davidmricardo , are you still got this working on Android 6+ ?
I've already updated the ZSDK_ANDROID_API to the latest version 2.14 but still doesn't work on newer versions of Android. I already removed the plugin and add it again with your changes but nothing seems to work. 

Thanks

**Comment by davidmricardo** [comment]
Hi,

Currently I'm working with android 8, I'm building my app with
cordova-android 6.4.0 and I'm using sdk 19 as min version and targeting sdk
26.

I'm being able to compile and use the printer.

I believe there are no diferences between my fork and the main repository,
Todd please check.

My fork is in https://github.com/davidmricardo/zebralink.git.

Are you having problems with gradle?

If so try this plugin:

cordova-android-support-gradle-release

I'm using it in version 1.4.5 and with the following configuration in
config.xml:

<plugin name="cordova-android-support-gradle-release" spec="~1.4.5">
        <variable name="ANDROID_SUPPORT_VERSION" value="13.+" />
    </plugin>

Hope this helps you.

If you want feel free to send me more details of your problems so I can
help you better.

Best Regards,
David

**Comment by davidmricardo** [comment]
I forgot, be sure to have the location permissions!

`<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
            <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
            <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
            <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />`

And in your mobile phone check the location permission in the app properties.

Whithout it in the discorey process it stalls, it give no error but does'nt do anything, just stands there trying. Also that permission isn't asked for so you need to check it manually!

If this solves your problem I suggest you use this:
cordova-plugin-android-permissions
With this plugin in can force your app to ask the user for location permission.

**Comment by phoenixtrigo** [comment]
Hi again @davidmricardo 

Well problem solved! 
It seems the problem was with location permission, after activated it on the app permissions it worked. Do you know why the bluetooth discovery needs the location ?! I'm confused with that. 


Thank you so much for the quick reply ! You saved my day!
Best regards,
André

**Comment by davidmricardo** [comment]
@phoenixtrigo <https://github.com/phoenixtrigo>

Great! I'm glad you solve it!

No, I have no idea why but it seems to be required from android 6 and later
versions.

From what I could find google did it for security reasons
https://developer.android.com/about/versions/marshmallow/android-6.0-changes#behavior-hardware-id

But I still can't find any relation between location permission and the
security issue they claim. I think it would make more sense to create a new
permission for this purpose.

Use the plugin I suggested so the users can easily grant location pemission.

I didn't like this:

function checkBluetoothPermission()
        {
            /*
            <uses-permission
android:name="android.permission.ACCESS_COARSE_LOCATION" />
            <uses-permission
android:name="android.permission.ACCESS_FINE_LOCATION" />
            <uses-permission
android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
            <uses-permission
android:name="android.permission.BLUETOOTH_ADMIN" />
            */
            if (!!window.cordova)
            {
                var permissions = cordova.plugins.permissions;

permissions.hasPermission(permissions.ACCESS_COARSE_LOCATION,
                        function (status) {
                            if (status.hasPermission) {
                                discover();
                            } else {

permissions.requestPermission(permissions.ACCESS_COARSE_LOCATION, function
(status) {
                                    if (!status.hasPermission) {
                                        //error();
                                    } else
                                    {
                                        discover();
                                    }
                                }, function () {

                                });

                            }
                        }
                );
            }
        }

And the app calls this function instead of calling discover directly!

**Comment by phoenixtrigo** [comment]
@davidmricardo 

Your code do the trick ;) 

It's strange they only need the permission to search devices, the other methods like connect and print works fine without it. 

Well thank you again
You save my day

With best regards,
André Trigo
